# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1395e48ac61a81e71c4e3d19a435b8779c23cdacf5cbe6670a33ec540984a53ab0b99b64e694e3cb8fa5e525e54d759da307312f5dd279c7a1a4195f007ff866

test:
  secret_key_base: 799f7ccc052aeb49053b5522288f9da36f230195c895f9bc7cd99e2f2772454e304daaaf7557518486c60df41c0a364f8ca1e0a6d2c602efb64864ba93919d5e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
